config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.resources :users

  map.resource :session

  map.resources :pesquisas

  map.resources :unidades

  map.resources :regiaos

  map.resources :sessions

  map.resources :gerenciars, :as => "gerencial"

  map.resources :homes

  map.resources :inscricaos, :collection => {:gera_pdf => :get,:listagem => :get,:checar => :get,:confirmacao => :get,:envia_email => :get,:estatistica => :get, :voltarinscricao => :get, :tipo_opcao => :get, :por_curso => :get}

  map.resources :cursos, :collection => {:voltar => :get}

  map.resources :participantes, :collection => {:busca_por_turno => :get,:consulta => :get,:voltarparticipante => :get}, :member => [:addemail,:update_email]

  

  map.root :controller => 'homes', :action => 'index'

  map.login 'login', :controller => 'sessions', :action => 'new'
  map.logout 'logout', :controller => 'sessions', :action => 'destroy'
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
  
end

app/models/inscricao.rb
class Inscricao < ActiveRecord::Base
  
  belongs_to :participante, :dependent => :destroy
  #belongs_to :opcao1, :class_name => 'Unidade', :foreign_key => "opcao1"
  #belongs_to :opcao2, :class_name => 'Unidade', :foreign_key => "opcao2"
  before_save :mesma_opcao
  has_and_belongs_to_many :cursos
  accepts_nested_attributes_for :participante
  validates_presence_of :participante_id
  validates_presence_of :opcao1, :if => :verifica_opcao
  validates_presence_of :opcao2, :if => :verifica_opcao2
  validates_uniqueness_of :participante_id, :message => " Error => Este participante já efetuou a inscrição"
  Periodo = %w(Matutino Vespertino Noturno Sabado_Matutino)

  def mesma_opcao
    unless self.opcao2.present?
      self.opcao2 = self.opcao1
      self.periodo_opcao2 = self.periodo_opcao1
    end
  end
  def verifica_opcao
    if self.opcao1 == ""
      true
    else
      false
    end
  end
    def verifica_opcao2
    if self.opcao2 == ""
      true
    else
      false
    end
  end

  def unidade(codigo)
    Unidade.find(codigo).nome
  end

end

app/controllers/inscricaos_controller.rb
class InscricaosController < ApplicationController
  # GET /inscricaos
  # GET /inscricaos.xml
    before_filter :load_cursos
    before_filter :load_participantes
    before_filter :load_inscricaos
    before_filter :load_locais
    
    layout :define


  def checar
    if params[:matricula]
      participante = Participante.find_by_matricula(params[:matricula])
      @inscricao = Inscricao.find_by_participante_id(participante)
    end
  end


  def envia_email
  end

  def confirmacao
    participante = Participante.find_by_matricula(params[:matricula])
    @inscricao = Inscricao.find_by_participante_id(participante.id)
    InscricaoMailer.deliver_confirmacao_inscricao(@inscricao,@inscricao.participante)

  end

  def kind
    t = 0
    y = 0
  end

  def define
    if logged_in?
      'gerenciar'
    else
      'cadastral'
    end
  end

  def index
    @inscricaos = Inscricao.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @inscricaos }
    end

  end

  # GET /inscricaos/1
  # GET /inscricaos/1.xml
  def show
    @inscricao = Inscricao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inscricao }
    end
  end

  # GET /inscricaos/new
  # GET /inscricaos/new.xml
  def new
    @inscricao = Inscricao.find_by_participante_id(params[:participante])
    if @inscricao.present?
      @participante = Participante.find(@inscricao.participante_id)
      redirect_to(edit_inscricao_path(@inscricao))
    else
      @inscricao = Inscricao.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @inscricao }
      end
    end
  end

  # GET /inscricaos/1/edit
  def edit
    @inscricao = Inscricao.find(params[:id])
  end


  def sel_participa
    @dadosparticipa = Participante.find(params[:inscricao_participante_id])
    @inscricao = Inscricao.find_by_participante_id(params[:inscricao_participante_id])
    render :update do |page|
      page.replace_html "informacoes", :partial => 'exibe_participante'
      if @dadosparticipa.possuidadosobrigatorios?
        page.replace_html "final", :text => "<input id='inscricao_submit' type='submit' value='Confirmar' name='commit'>"
      else
        page.replace_html "final", :text => "<a href='/participantes/#{params[:inscricao_participante_id]}/addemail'>Favor atualizar dados</a>"
      end
    end
  end
  # POST /inscricaos
  # POST /inscricaos.xml
  def create
    @inscricao = Inscricao.new(params[:inscricao])
    @inscricao.data_inscricao = Time.now
    respond_to do |format|
      if @inscricao.save
        flash[:notice] = 'INSCRIÇÃO CONFIRMADA COM SUCESSO.'
        InscricaoMailer.deliver_confirmacao_inscricao(@inscricao,@inscricao.participante)
        format.html { redirect_to(@inscricao) }
        format.xml  { render :xml => @inscricao, :status => :created, :location => @inscricao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @inscricao.errors, :status => :unprocessable_entity }
      end

    end
  end

  # PUT /inscricaos/1
  # PUT /inscricaos/1.xml
  def update
    @inscricao = Inscricao.find(params[:id])


    respond_to do |format|
      if @inscricao.update_attributes(params[:inscricao])
        flash[:notice] = 'INSCRIÇÃO ATUALIZADA COM SUCESSO.'
        format.html { redirect_to(@inscricao) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @inscricao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /inscricaos/1
  # DELETE /inscricaos/1.xml
  def destroy
    @inscricao = Inscricao.find(params[:id])
    @inscricao.destroy

    respond_to do |format|
      format.html { redirect_to(inscricaos_url) }
      format.xml  { head :ok }
    end
  end


 def por_curso
   @search = Inscricao.search(params[:search])
   if (params[:search]).present?
    @curso = @search.paginate(:all,:page=>params[:page],:per_page =>20, :order => sort_column + " " + sort_direction)
   end
   render :action => 'por_curso'
 end

  def gera_pdf
   @search = Curso.find(params[:curso])
   unless session[:unidade].present?
     @contador = @cursos_inscricaos = Inscricao.all({:include => 'cursos',:conditions => [ 'cursos.id =? ', @search.id]})
     #@contador = Inscricao.all(:include => 'cursos',:conditions => [ 'cursos.id =? ', @search.id])
   else
     if session[:opcao] == "Todos"
       @cursos_inscricaos = Inscricao.all({:include => 'cursos',:conditions => [ 'cursos.id =? and (inscricaos.opcao1 = ? and inscricaos.periodo_opcao1 = ?)', @search.id,session[:unidade], session[:opcao] ], :order =>"inscricaos.id"})
     else
       @cursos_inscricaos = Inscricao.all({:include => 'cursos',:conditions => [ 'cursos.id =? and (inscricaos.opcao1 = ?)', @search.id,session[:unidade] ], :order =>"inscricaos.id"})              
     end
     @contador = Inscricao.all(:include => 'cursos',:conditions => [ 'cursos.id =? ', @search.id])
   end
    respond_to do |format|
      format.html {render(:layout => false)} ## index.html.erb
      format.pdf do
        html = render_to_string(:layout => 'false' , :action => "gera_pdf.erb")
        kit = PDFKit.new(html)
        kit.stylesheets << "#{Rails.root}/public/stylesheets/pdf.css"
        send_data(kit.to_pdf, :filename => "#{@search.nome_curto}.pdf", :type => 'application/pdf')
      end
    end
 end


 def listagem
   if params[:curso].present?
     session[:opcao] = params[:periodo_opcao1]
     session[:unidade] = params[:curso][:unidade]
     @search = Curso.find(params[:curso][:get])
     unless session[:unidade].present?
       #@cursos_inscricaos = Inscricao.paginate(:all, {:page => params[:page],:per_page => 10, :include => 'cursos',:conditions => [ 'cursos.id =? ', @search.id]})
       @inscricao=@contador = Inscricao.all(:include => 'cursos',:conditions => [ 'cursos.id =? ', @search.id])
     else
       #@cursos_inscricaos = Inscricao.paginate(:all, {:page => params[:page],:per_page => 10, :include => 'cursos',:conditions => [ 'cursos.id =? and (inscricaos.opcao1 = ? and inscricaos.periodo_opcao1 = ?)', @search.id,session[:unidade], session[:opcao] ]})
       @inscricao=@contador = Inscricao.all(:include => 'cursos',:conditions => [ 'cursos.id =? and (inscricaos.opcao1 = ? and inscricaos.periodo_opcao1 = ?)', @search.id,session[:unidade], session[:opcao] ])
     end
     @cursos_inscricaos = @inscricao.paginate({:page => params[:page],:per_page => 10})
     gera_excel(@inscricao)
   end
 end


 def gera_excel(inscricao)
        ## Gera arquivo em pdf
     #@inscricao = Inscricao.all(:include => "cursos",:conditions => [ 'cursos.id =1' ])
     @report = DailyOrdersXlsFactory.new("simple report")
     @report.add_column(10).add_column(40).add_column(30).add_column(30).add_column(30)
     @report.add_row(["Prefeitura Municipal de Americana"], 30).join_last_row_heading(0..6)
     @report.add_row(["Inscritos no curso: #{@search.truncar_curso} "], 30).join_last_row_heading(0..6)
     @report.add_row(["Matricula","Nome","Unidade","Opção 1","Horario","Opçao 2","Horario"])
     inscricao.each do |insc|
       @report.add_row([insc.participante.matricula,insc.participante.nome,insc.participante.unidade.nome,insc.unidade(insc.opcao1),insc.periodo_opcao1,insc.unidade(insc.opcao2),insc.periodo_opcao2])
     end
     @rel = Relatorio.new
       @rel.ip = request.remote_ip
       @rel.user_id = current_user
       @rel.path = @report.save_to_file("public/saidas/#{@search.truncar_curso}_#{Date.today.strftime("%d_%m_%Y")}_#{@rel.user.login}.xls")
     @rel.save

 end

 def lista_inscricao
    $curso = params[:curso_curso_id]
    @inscricaos = Inscricao.find(:all, :conditions => ['curso_id=' + $curso ])
    render :partial => 'lista_inscricao'
 end

 def estatistica
    @cursos = Curso.find(:all, :order => 'nome ASC')
    @inscricaos = Inscricao.all
  end

private

  def sort_column
    Inscricao.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



protected


  def load_locais
    @locais = Unidade.all(:conditions => ["id in (42,43,44,45,46,47,48,49,50,51)"])
  end

  def load_inscricaos
    @inscricaos = Inscricao.find(:all)
  end

  def load_cursos
    @cursos = Curso.find(:all, :order => 'nome ASC')
  end


  def load_participantes
    if params[:participante].present?
      @participante = Participante.find(params[:participante], :order => 'nome ASC')
    else
      @participantes = Participante.find(:all, :order => 'nome ASC')
    end
  end


end

app/helpers/inscricaos_helper.rb
module InscricaosHelper
end

app/views/inscricaos/_email_unitario.html.erb
          <% form_tag confirmacao_inscricaos_path, :method => 'get' do %>
            <%= label_tag :matricula, "Digite o matricula: "  %><%= text_field_tag :matricula%>
            <%= submit_tag "Buscar", :name => nil %>
          <% end %>

app/views/inscricaos/_exibe_cursos.erb
<% for curso in @cursosparticipa %>
     <b>Nome:<%=h curso.nome %><br/>
        Ministrante: <%=h curso.ministrante %><br/>
        Tipo: <%=h curso.tipo %><br/>
        Carga Horaria: <%=h curso.carga_horaria%> horas<br/>
        Data e Horário:<%=h curso.data_hora.strftime("%d de %B de %Y - %H:%M horas") %><br/>
        Observações:<%=h curso.obs %>
      </b>
     <% end %>

app/views/inscricaos/_form.html.erb
<% form_for(@inscricao) do |f| %>
 <%= f.error_messages %>
  <p>
    <b>Participante:</b>
    <% if @participante.present? %>
      <%= @participante.nome %>
      <%= f.hidden_field(:participante_id,:value => @participante.id) %>
    <%else%>
      <%= f.collection_select :participante_id, @participantes, :id, :nome, :include_blank => ' -- Selecione -- ' %>
    <%end%>
    <%= observe_field  :inscricao_participante_id,
                       :with => :inscricao_participante_id,
                       :url => { :action => 'sel_participa' } %>
  </p>
  <p>
    <%if @participante.present?%>
      Matricula: <%=h @participante.matricula %><br/>
      Nome:<%=h @participante.nome %><br/>
      Cidade:<%=h @participante.cidade %><br/>
      Email:<%=h @participante.email %><br/>
      Observações: <%=h @participante.obs %><br/>
    <%else%>
      <div id="informacoes"></div>
    <%end%>
  </p>

  <table class="tabelas">
    <th colspan="2" style=" font-size: large; color: blue">Cursos</th>
    <% @cursos.in_groups_of(2, false) do |row_cursos| %>
      <tr>
        <% row_cursos.each do |curso| %>
          <td id="demo" align="left"><%= check_box_tag "inscricao[curso_ids][]", curso.id, @inscricao.cursos.include?(curso), :title => "#{curso.ementa}"%><%= curso.nome_curto %></td>
        <% end %>
      </tr>
    <%end%>
      <tr>
        <th colspan="2" style=" font-size: large; color: blue">* Para maiores informações sobre os cursos, posicione o mouse sobre as caixas de opção</th>
      </tr>
  </table>

  <p>
    <fieldset><legend>Opção de unidades</legend>
      <b>Opção 1</b>
      <%= f.collection_select :opcao1, @locais, :id, :nome, :include_blank => ' -- Selecione -- ' %>
      <b>Turno</b>
      <%= f.select :periodo_opcao1, options_for_select(Inscricao::Periodo), :include_blank => "" %><br/>

      <b>Opção 2</b>
      <%= f.collection_select :opcao2, @locais, :id, :nome, :include_blank => ' -- Selecione -- ' %>
      <b>Turno</b>
      <%= f.select :periodo_opcao2, options_for_select(Inscricao::Periodo), :include_blank => "" %><br/>
    </fieldset>
  </p>

  <p>
    <div id="final"><%= f.submit "Confirmar suas opções"  %></div>
  </p>
<%end%>

app/views/inscricaos/_inscritos.html.erb
  <%if @search.present?%>
  <%= link_to image_tag("/stylesheets/images/pdf.png", :size => "40x40"), gera_pdf_inscricaos_path(:format => "pdf", :curso => @search) %>
  <%= link_to image_tag("/stylesheets/images/excel.gif", :size => "40x40"),@rel.path_truncado %>
  <table class="tabelas">
    <tr><td colspan="4"><h3><%= "No total #{@search.inscricaos.count} estão inscritos neste curso." %></h3></td></tr>
    <tr><td colspan="4"><h4><%= "Para esta seleção #{@contador.count} inscritos." %></h4></td></tr>
    <% unidade = session[:unidade].present? ? Unidade.find(session[:unidade]).nome : "Geral" %>
    <tr><td colspan="3"><%= "Unidade: #{unidade}: " %></td><td><%= "Unidade: #{session[:opcao]}" %></td></tr>

    <tr>
      <th class="numero">Matricula</th>
      <th class="tamanho_tab">Nome</th>
      <th class="tamanho_tab">Opção 1</th>
      <th class="tamanho_tab">Opção 2</th>
    </tr>

    <% @cursos_inscricaos.each do |inscrito| %>
      <tr>
        <td class="numero"><%= inscrito.participante.matricula%></td>
        <td class="tamanho_tab"><%= inscrito.participante.nome%></td>
        <td class="tamanho_tab"><%= "#{Unidade.find(inscrito.opcao1).nome} - #{inscrito.periodo_opcao1}"%></td>
        <td class="tamanho_tab"><%= "#{Unidade.find(inscrito.opcao2).nome} - #{inscrito.periodo_opcao1}"%></td>
      </tr>
    <%end%>
      <tr><td colspan="3"><%= will_paginate @cursos_inscricaos %></td></tr>
  </table>
  <%end%>

app/views/inscricaos/_lista_inscricao.html.erb
<style media="print">
.botao {
display: none;
}
</style>
<br/>
<table>
 <tr>
   <td align="left"l><font size="4"><b><u> Resultado da Consulta</u></b></font></td>
   <br/>
 </tr>
 <tr>
  <td width="100%" colspan="3">
   <%  $contador = 0 %>
   <table border ="1" cellpadding="1" cellspacing="1" width="100%" >
       <tr>
        <td bgcolor="gray">Participante</td>
        <td bgcolor="gray">Curso</td>
        <td bgcolor="gray">Tipo</td>
        <td bgcolor="gray">Data da Inscrição:</td>
      </tr>
      <% for inscricao in @inscricaos %>
      <tr>
       <td><%=h inscricao.participante.nome %></td>
       <td><%=h inscricao.curso.nome %></td>
       <td><%=h inscricao.curso.tipo %></td>
       <td><%=h inscricao.data_inscricao.strftime("%d de %B de %Y") %> </td>
     </tr>
     <%  $contador = $contador + 1 %>
    <% end %>
   </table>
 </td>
</tr>

<tr>
     <td width="8%" colspan="4"><b> Total de inscritos no curso: <%= $contador %></b> </td>
     </tr>
 </table>

app/views/inscricaos/checar.html.erb
    <% form_tag :action => "checar", :controller => "inscricaos", :method => :get,:loading => "$('#status').show()" , :success => "$('#status').hide()" do %>
         <table width="100%">
          <tr>
            <td>
               <%= label_tag :matricula, "Matricula" %>
               <%= text_field_tag(:matricula) %>
            </td>
            <td>
              <%= submit_tag "Buscar" %>
            </td>
         </tr>
        </table>
    <% end %>


<% if @inscricao.present? %>
<p>
<h1><%= "Parabéns #{@inscricao.participante.nome}" %></h1>
<b><%= "Sua inscrição nos modulos de treinamento foi efetuada com sucesso." %></b>
<b><%=  "Inscricao nº: #{@inscricao.id}" %></b><br/>
<b>
  <%= "Você esta inscrito nos seguintes módulos" %>
  <ul>
    <% @inscricao.cursos.each do |inscricao| %>
        <li><%= inscricao.nome %></li>
    <%end%>
  </ul>
  <p><%=h "Local de interesse 1: #{Unidade.find(@inscricao.opcao1).nome} - #{@inscricao.periodo_opcao1}" %></p>
  <p><%=h "Local de interesse 2: #{Unidade.find(@inscricao.opcao2).nome} - #{@inscricao.periodo_opcao2}" %></p>

  <h2>Agradecemos por sua inscrição</h2>
  <h2>Equipe de Informática - SEDUC</h2>
  <h2>Prefeitura de Americana</h2>
</b>
</p>

<%end%>

app/views/inscricaos/confirmacao.html.erb
<% if @inscricao.present? %>
<p>
<h1><%= "Parabéns #{@inscricao.participante.nome}" %></h1>
<b><%= "Sua inscrição nos modulos de treinamento foi efetuada com sucesso." %></b>
<b><%=  "Inscricao nº: #{@inscricao.id}" %></b><br/>
<b>
  <%= "Você esta inscrito nos seguintes módulos" %>
  <ul>
    <% @inscricao.cursos.each do |inscricao| %>
        <li><%= inscricao.nome %></li>
    <%end%>
  </ul>
  <p><%=h "Local de interesse 1: #{Unidade.find(@inscricao.opcao1).nome} - #{@inscricao.periodo_opcao1}" %></p>
  <p><%=h "Local de interesse 2: #{Unidade.find(@inscricao.opcao2).nome} - #{@inscricao.periodo_opcao2}" %></p>

  <h2>Agradecemos por sua inscrição</h2>
  <h2>Equipe de Informática - SEDUC</h2>
  <h2>Prefeitura de Americana</h2>
</b>
</p>

<%end%>

app/views/inscricaos/edit.html.erb
 <br/>
 <br/>
 <table width="90%" border="1" align="center">
   <tr>
     <td>
        <h1 align="center">Alterar Inscrição</h1>
      </td>
   </tr>
   <tr>
      <td>
         <table border="3" width="100%">
           <tr>
            <td>
              <%= render "form" %>
            </td>
           </tr>
         </table>
      </td>
   </tr>
  </table>
  <script>
    $("#demo input[title]").tooltip();
  </script>

app/views/inscricaos/envia_email.html.erb
    <% form_remote_tag :action => "kind", :controller => "inscricaos", :method => :get,:loading => "$('#status').show()" , :success => "$('#status').hide()" do %>
         <table width="100%" align="center" bgcolor="#DCDCDC" >
          <tr>
            <td>
               <a href="#"><%= radio_button_tag(:type_of, "1") %></a>Unitario
            </td>
            <td>
               <a href="#"><%= radio_button_tag(:type_of, "2") %></a>Geral
            </td>
         </tr>
         <tr>
           <td><div class="envia_individual" style="display:none"> <%= render "/shared/consulta_individual" %> </div></td>
           <td><div class="envia_geral" style="display:none"> <%= render "/shared/consulta_geral" %> </div></td>
         </tr>
        </table>
    <% end %>

app/views/inscricaos/gera_pdf.erb
<table>
    <tr>
      <td colspan="2">
        <h1>Prefeitura Municipal de Americana</h1>
      </td>
    </tr>
    <tr>
      <td colspan="2">Americana - ____ / __________ / ______</td>
    </tr>
    <tr><td><%= "Ministrante:_______________" %></td></tr>
</table>
<table border="1" frame="border" rules="rows">
  <tr><td colspan="3"><h2><%= "Listagem de presença" %></h2></td></tr>
  <tr><td colspan="3"><b><%= "Curso - #{Curso.find(params[:curso]).nome_curto}" %></b><br/></td></tr>
  <% unidade = session[:unidade].present? ? Unidade.find(session[:unidade]).nome : "Geral" %>
  <% opcao = session[:opcao].present? ? session[:opcao] : "Todas" %>
  <tr><td colspan="2"><%= "Unidade: #{unidade}" %></td><td><%= "Opção: #{opcao}" %></td></tr>
  <tr>
    <th class="numero">Id</th>
    <th>Participante</th>
    <th>Assinatura</th>
  </tr>
  <%contador = 1%>  
  <% @cursos_inscricaos.each do |inscrito| %>
    <tr>
      <td class="numero"><%= contador%></td>
      <td><%= inscrito.participante.nome %></td>
      <td></td>
    </tr>
    <%contador += 1%>
  <%end%>
</table>

app/views/inscricaos/index.html.erb
<div id="conteudo">
<fieldset> <legend><font size=6> Inscrições Realizadas</font></legend>
  <br/>
   <%= button_to 'Nova Inscrição', new_inscricao_path %>
   <br/>
    <table border="2">
      <tr>
        <td bgcolor="gray">Participante</td>
        <td bgcolor="gray">Curso</td>
        <td bgcolor="gray">Tipo</td>
         <td bgcolor="gray">Data da Inscrição:</td>
      </tr>
      <% for inscricao in @inscricaos %>
      <tr>
       <td bgcolor="gray"><%=h inscricao.participante.nome %></td>
       <td bgcolor="gray"><%=h inscricao.curso.nome %></td>
       <td bgcolor="gray"><%=h inscricao.curso.tipo %></td>
       <td bgcolor="gray"><%=h inscricao.data_inscricao.strftime("%d de %B de %Y") %> </td>
     </tr>
     <tr>
       <td bgcolor="gray"colspan="5">
         |<%= link_to 'Exibir', inscricao %>|
         <!--<%= link_to 'Apagar', inscricao, :confirm => 'Confirma?', :method => :delete %>|-->

     </tr>
     <% end %>
    </table>
</fieldset>
   <%= button_to 'Nova Inscrição', new_inscricao_path %>
</div>

app/views/inscricaos/new.html.erb
<br/>
<div class="sombra">
  <div class="formulario">
    <div class="form_title"><h1 align="center" >Inscrição</h1></div>
    <div class="form_body">
      <fieldset>
        <%= render "form" %>
      </fieldset>
      <p>Ainda não está cadastrado???? Clique no botão abaixo para efetuar seu cadastro.</p>
      <p><%= link_to 'Cadastre-se já', new_participante_path, :class => "link" %></p>
    </div>
  </div>
</div>


  <script>
    $("#demo input[title]").tooltip();
  </script>

app/views/inscricaos/por_curso.html.erb
 <br/>
 <br/>
     <table width="100%">
      <tr>
        <% form_for @search do |f| %>
          <tr>
            <td align="right">
              <%= f.label :cursos_id_equals, "Curso" %>
              <%= f.select :cursos_id_equals, Curso.all.collect {|p| [ p.nome_curto, p.id ]}, :include_blank => true%>
            </td>
            <td align="center" colspan="2">
              <%= f.submit "Buscar" %>
            </td>
          </tr>
        <% end %>
      </tr>
    </table>
    
      <table width="100%"  class="tabelas">
        <tr style="font-size:12px">
         <br/>
        </tr>

        <%if @curso.present? %>
            <h1 align="center">Inscrições para o curso:  <%= params[:search] ? Curso.find(params[:search][:cursos_id_equals]).nome_curto : "Selecione" %></h1>
            <tr>
              <th>Matricula</th>
              <th>Nome</th>
              <th>Pertence a Unidade</th>
            </tr>
            <% @curso.each do |inscricao| %>
              <tr>
                <td align="center"><%=h inscricao.participante.matricula %></td>
                <td align="center"><%=h inscricao.participante.nome %></td>
                <%  if inscricao.participante.tipo_participante == 2 %>
                  <td align="center"><%=h "Externo" %></td>
                <%else%>
                  <td align="center"><%=h inscricao.participante.unidade.nome %></td>
                <%end%>
              </tr>
            <%end%>
        <tr>
          <td colspan="3"><br/></td>
        </tr>
        <tr>
          <td colspan="3" align="center"> <b><%= "Existe(m) #{@curso.count} participante(s) inscrito(s) neste curso" %></b></td>
        </tr>
      <% end %>
      </table>

      <%= @curso ? (will_paginate @curso) : "" %>

  <div class="botao">
   <table width="100%" align="center">
    <tr>
      <br/>
      <td width="8%"><%= button_to 'Voltar', gerenciars_path, {:method => 'get'}%></td>
    </tr>
  </table>
  </div>

app/views/inscricaos/show.html.erb
 <br/>
 <br/>
 <table width="70%" border="1" frame="box" rules="all" align="center">
   <tr>
     <td>
        <h1 align="center">Confirmação da Inscrição</h1>
      </td>
   </tr>
   <tr>
      <td>
       <table width="100%" border="1">
         <br/>
           <tr>
             <th colspan="2"><b>Participante:</b></th>
           </tr>
           <tr>
             <td colspan="2">
              <%=h  @inscricao.participante.nome %>
             </td>
           </tr>
      <tr>
          <th colspan="2">Cursos:</th>
      </tr>
          <% @inscricao.cursos.each do |curso| %>
              <tr>
                <td colspan="2" align="center">
                  <b><%=h curso.nome %></b>
                </td>
              </tr>
            <tr>
              <td><%=h "Opção1: #{Unidade.find(@inscricao.opcao1).nome} - #{@inscricao.periodo_opcao1}" %></td>
              <td><%=h "Opção2: #{Unidade.find(@inscricao.opcao2).nome} - #{@inscricao.periodo_opcao2}" %></td>
            </tr>
          <% end %>
          <tr>
            <td colspan="2"><b>Inscrição efetuada em:</b>
              <%=h  @inscricao.data_inscricao.strftime("%d de %B de %Y") %> </td>
          </tr>
          <tr>
            <td colspan="2">
              <b>Você já está pré-inscrito nos módulos acima, a partir do momento que os mesmos forem efetivados, enviaremos uma notificação via e-mail. Todas estas informações foram enviadas ao email informado.</b>
            </td>
          </tr>
       </table>
     </td>
   </tr>
  </table>
  <div class="botao">
   <table width="70%" align="center">
    <tr>
       <td width="8%"><%= button_to 'Nova Inscrição', new_inscricao_path  %></td>
       <td><input type="Button" Value="Imprimir" onclick="javascript:window.print()"></td>
    </tr>
  </table>
 </div>